/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <time.h>
#include <sys/dir.h>
#include <sys/param.h>
#include <rpc/rpc.h>
#include <dirent.h>
#include <string.h>
#include <unistd.h>
#include "DFS.h"

char **
getdir_1_svc(void *argp, struct svc_req *rqstp)
{
	static char *getdir_res;

	if ((getdir_res = getcwd(NULL, 0)) == NULL)
	{
		getdir_res = NULL;
	}
	return &getdir_res;
}

bool_t *
changedir_1_svc(char **argp, struct svc_req *rqstp)
{
	static bool_t cd_res;

	cd_res = (chdir(*argp) == -1) ? 0 : 1;

	return &cd_res;
}
DIR *pdir;

int *filecount_1_svc(void *argp, struct svc_req *rqstp)
{
	static int counts;
	int tmp = 0;
	struct dirent *dr;
	DIR *tdir;

	tdir = opendir(".");
	while ((dr = readdir(tdir)) != NULL)
    {
		/*if(strcmp(dr->d_name, ".") != 0 && strcmp(dr->d_name, "..") != 0 ){}*/
        	++tmp;
    }
	closedir(tdir);

	counts = tmp;
	return &counts;
}

bool_t *
openlist_1_svc(char **argp, struct svc_req *rqstp)
{
	static bool_t op_res;
	pdir = opendir(*argp);
	op_res = (pdir == NULL) ? 0 : 1;
	return &op_res;
}

direntry *
nextlist_1_svc(void *argp, struct svc_req *rqstp)
{
	static direntry dir;
	struct dirent *dr;
	struct stat attrs;

	if ((dr = readdir(pdir)) == NULL)
	{
		dir.flag = -1;
		return &dir;
	}

	strcpy(dir.entryname, dr->d_name);
	dir.flag = (int)dr->d_type;
	stat(dir.entryname, &attrs);
	strftime(dir.date, 255, "%Y-%m-%d %H:%M:%S", localtime(&attrs.st_mtime));
	dir.size = attrs.st_size;
	return &dir;
}

bool_t *
closelist_1_svc(void *argp, struct svc_req *rqstp)
{
	static bool_t close_d_res;

	close_d_res = (closedir(pdir) == 0) ? 1 : 0;
	return &close_d_res;
}

bool_t *
openfiletowrite_1_svc(char **argp, struct svc_req *rqstp)
{
	static bool_t result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
nextwrite_1_svc(file_block *argp, struct svc_req *rqstp)
{
	static bool_t result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
closefile_1_svc(void *argp, struct svc_req *rqstp)
{
	static bool_t result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
openfiletoread_1_svc(char **argp, struct svc_req *rqstp)
{
	static bool_t result;

	/*
	 * insert server code here
	 */

	return &result;
}

file_block *
nextread_1_svc(void *argp, struct svc_req *rqstp)
{
	static file_block result;

	/*
	 * insert server code here
	 */

	return &result;
}

file_block *
randomread_1_svc(file_block *argp, struct svc_req *rqstp)
{
	static file_block result;

	/*
	 * insert server code here
	 */

	return &result;
}
